let dados = [
    {
        versiculos: "Amor",
        lista: "<b> 1 Coríntios 13:4-7: </b> O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha. Não maltrata, não procura seus interesses, não se ira facilmente, não guarda rancor. O amor não se alegra com a injustiça, mas se alegra com a verdade. <br> <b> João 3: 16: </b> Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna. <br> <b> Romanos 5:8: </b> Mas Deus demonstra o seu amor para conosco, em que, estando nós ainda pecadores, Cristo morreu por nós. <br> <b> 1 João 4:8: </b> Quem não ama não conhece a Deus, porque Deus é amor. <br> <b> Efésios 5:2: </b> Andai em amor, assim como Cristo nos amou e se entregou por nós em oferta e sacrifício a Deus, em aroma suave.",
        link: "https://www.bibliaonline.com.br/",
        tags: "raiva amor paixão compaixão perdão sacrifício amizade família relacionamento emoções vida Deus graça misericórdia",
    },
    {
        versiculos: "Ansiedade",
        lista: "<b> Filipenses 4:6: </b> Não se preocupem com nada, mas em todas as orações, com pedidos e agradecimentos, apresentem seus pedidos a Deus. <br> <b> João 14:27: </b> Deixo-lhes a paz; a minha paz lhes dou. Não a dou como o mundo a dá. Não se perturbe o coração de vocês. Creiam em Deus; creiam também em mim. <br> <b> Salmos 46:1: </b> Deus é o nosso refúgio e fortaleza, socorro bem presente nas tribulações. <br> <b> Mateus 6:34:</b>  Portanto não se preocupem com o dia de amanhã, pois o dia de amanhã cuidará de si mesmo. Basta a cada dia o seu próprio mal. <br> <b> 1 Pedro 5:7: </b> Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês.",
        link: "https://www.bibliaonline.com.br/",
        tags: "medo desespero ansiedade estresse preocupação insegurança futuro controle medo desespero paz esperança fé Deus",
    },
    {
        versiculos: "Amor de Deus",
        lista: "<b> João 3:16: </b> Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.<br> <b> Romanos 5:8:</b> Mas Deus demonstra o seu amor para conosco, em que, estando nós ainda pecadores, Cristo morreu por nós. <br> <b> 1 João 4:8: </b> Quem não ama não conhece a Deus, porque Deus é amor. <br> <b> 1 Coríntios 13:4-7: </b> O amor é paciente, o amor é bondoso. Não tem inveja, não se vangloria, não se orgulha. Não é rude, não busca os seus próprios interesses, não se irrita, não guarda rancor. O amor não se alegra com a injustiça, mas se alegra com a verdade. Tudo sofre, tudo crê, tudo espera, tudo suporta. <br> <b> Efésios 2:4-5: </b> Mas Deus, sendo rico em misericórdia, por causa do grande amor com que nos amou, mesmo estando nós mortos em nossas transgressões, nos vivificou juntamente com Cristo (pela graça sois salvos).",
        link: "https://www.bibliaonline.com.br/",
        tags:"desespero medo suicídio graça misericórdia redenção salvação sacrifício",
    },
    {
        versiculos: "Amor ao Próximo",
        lista: "<b> Mateus 22:39: </b> Amarás o teu próximo como a ti mesmo. <br> <b> Gálatas 5:13: </b> Porque toda a Lei se cumpre em um só mandamento, qual seja este: Amarás o teu próximo como a ti mesmo. <br> <b> Romanos 13:8: </b> A ninguém deveis nada, a não ser o amor uns aos outros; pois quem ama ao próximo cumpriu a Lei. <br> <b> João 13:34: </b> Um novo mandamento lhes dou: que se amem uns aos outros. Assim como eu os amei, vocês também devem amar uns aos outros. Nisto todos conhecerão que vocês são meus discípulos, se amarem uns aos outros. <br> <b> 1 Coríntios 13:7: </b> O amor tudo sofre, tudo crê, tudo espera, tudo suporta.",
        link: "https://www.bibliaonline.com.br/",
        tags:"vingança ajuda serviço bondade compaixão empatia justiça",
    },
    {
        versiculos: "Salvação e Vida Eterna",
        lista: "<b> João 14:6: </b> Jesus lhe disse: Eu sou o caminho, e a verdade, e a vida; ninguém vem ao Pai, senão por mim. <br> <b> Romanos 6:23: </b> Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor. <br> <b> Efésios 2:8: </b> Porque pela graça sois salvos, por meio da fé; e isto não vem de vós, é dom de Deus. <br> <b> Tito 3:5: </b> Não por obras de justiça que nós havemos praticado, mas segundo a sua misericórdia nos salvou, por meio da lavagem da regeneração e da renovação pelo Espírito Santo. <br> <b> Apocalipse 22:17: </b> E o Espírito e a noiva dizem: Vem! E quem ouvir, diga: Vem! E quem tiver sede, venha; e quem quiser, tome gratuitamente da água da vida.",
        link: "https://www.bibliaonline.com.br/",
        tags:"morte céu inferno julgamento ressurreição novo nascimento",
    },
    {
        versiculos: "Fé e Confiança em Deus",
        lista: "<b> Hebreus 11:1: </b> Ora, a fé é a certeza de coisas que se esperam, a convicção de fatos que se não veem. <br> <b> Romanos 1:17: </b> Porque no evangelho a justiça de Deus se revela, de fé em fé, como está escrito: O justo viverá por fé. <br> <b> Marcos 11:22: </b> E Jesus, respondendo, lhes disse: Tende fé em Deus. <br> <b> 2 Coríntios 5:7: </b> Porque andamos por fé, e não por vista. <br> <b> Salmos 46:1: </b> Deus é o nosso refúgio e fortaleza, socorro bem presente nas tribulações.",
        link: "https://www.bibliaonline.com.br/",
        tags:"medo desespero esperança milagres provações dúvida oração",
    },
    {
        versiculos: "Propósito da Vida",
        lista: "<b> Jeremias 29:11: </b> Porque eu bem sei os pensamentos que tenho a vosso respeito, diz o Senhor; pensamentos de paz, e não de mal, para vos dar o fim que esperais. <br> <b> Mateus 22:37-39: </b> E Jesus lhe disse: Amarás o Senhor, teu Deus, de todo o teu coração, e de toda a tua alma, e de todo o teu entendimento. Este é o primeiro e grande mandamento. E o segundo, semelhante a este, é: Amarás o teu próximo como a ti mesmo.<br> <b> Efésios 2:10: </b> Porque somos obra de Deus, criados em Cristo Jesus para boas obras, as quais Deus de antemão preparou para que andássemos nelas. <br> <b> Filipenses 1:21: </b> Porque para mim o viver é Cristo, e o morrer é ganho.<br> <b> Colossenses 3:23: </b> E tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor, e não aos homens.",
        link: "https://www.bibliaonline.com.br/",
        tags:"suicídio carreira chamado missão significado sucesso fracasso",
    },
    {
        versiculos: "Moralidade e Ética",
        lista: "<b>Romanos 12:2:</b> E não vos conformeis com este século, mas transformai-vos pela renovação do vosso entendimento, para que proveis qual seja a boa, agradável e perfeita vontade de Deus. <br> <b> Mateus 7:12: </b> Portanto, tudo quanto quereis que os homens vos façam, assim também fazei-vos a eles, pois esta é a lei e os profetas. <br> <b> Efésios 4:25: </b> Por isso, rejeitando a mentira, falai a verdade cada um com o seu próximo, porque somos membros uns dos outros. <br> <b> Tiago 1:22: </b> Mas sede cumpridores da palavra, e não somente ouvintes, enganando-vos a vós mesmos. <br> <b> 1 Pedro 2:15: </b> Porque assim lhes agrada a Deus: que, praticando o bem, façam calar as bocas da ignorância dos homens insensatos.",
        link: "https://www.bibliaonline.com.br/",
        tags:"mentira justiça honestidade integridade valores conduta",
    },
    {
        versiculos: "Bondade",
        lista: "<b>Romanos 12:2:</b> E não vos conformeis com este século, mas transformai-vos pela renovação do vosso entendimento, para que proveis qual seja a boa, agradável e perfeita vontade de Deus. <br> <b> Mateus 7:12: </b> Portanto, tudo quanto quereis que os homens vos façam, assim também fazei-vos a eles, pois esta é a lei e os profetas. <br> <b> Efésios 4:25: </b> Por isso, rejeitando a mentira, falai a verdade cada um com o seu próximo, porque somos membros uns dos outros. <br> <b> Tiago 1:22: </b> Mas sede cumpridores da palavra, e não somente ouvintes, enganando-vos a vós mesmos. <br> <b> 1 Pedro 2:15: </b> Porque assim lhes agrada a Deus: que, praticando o bem, façam calar as bocas da ignorância dos homens insensatos.",
        link: "https://www.bibliaonline.com.br/",
        tags:"generosidade altruísmo compaixão serviço",
    },
    {
        versiculos: "Esperança",
        lista: "<b> Romanos 15:13: </b> Ora, o Deus da esperança vos encha de todo o gozo e paz, em crer, para que abundeis em esperança pelo poder do Espírito Santo. <br> <b> 1 Tessalonicenses 1:3: </b> Lembrando-nos sem cessar da vossa obra de fé, do trabalho de amor e da perseverança da esperança em nosso Senhor Jesus Cristo, diante de nosso Deus e Pai. <br> <b> Tito 1:2: </b> Na esperança da vida eterna, a qual Deus, que não mente, prometeu antes dos tempos dos séculos, <br> <b> Hebreus 6:19: </b>  Esta esperança temos como âncora da alma, firme e segura, e que penetra até ao interior do véu, <br> <b> 1 Pedro 1:3: </b> Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, que, segundo a sua grande misericórdia, nos regenerou para uma viva esperança, mediante a ressurreição de Jesus Cristo dentre os mortos,",
        link: "https://www.bibliaonline.com.br/",
        tags:"fé, futuro, positividade, otimismo, consolo, paz, alegria, encorajamento, confiança, perseverança, salvação, vida eterna, promessa, reino de Deus",
    },
    {
        versiculos: "Perdão",
        lista: "<b> Mateus 6:14: </b> Porque, se perdoardes aos homens as suas ofensas, também vosso Pai celestial vos perdoará; <br> <b> Efésios 4:32: </b> Antes, sede uns para com os outros benignos, compassivos, perdoando-vos mutuamente, assim como Deus vos perdoou em Cristo. <br> <b> Colossenses 3:13: </b> Suportando-vos uns aos outros, e perdoando-vos mutuamente, se alguém tiver queixa contra outro; assim como Cristo vos perdoou, assim fazei vós também. <br> <b> Lucas 6:37: </b> E não julgueis, e não sereis julgados; e não condeneis, e não sereis condenados; perdoai, e sereis perdoados; <br> <b> 1 João 1:9: </b> Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda a injustiça.",
        link: "https://www.bibliaonline.com.br/",
        tags:"arrependimento, reconciliação, libertação, amor, compaixão",
    },
    {
        versiculos: "Misericórdia",
        lista: "<b> Salmo 103:8: </b> O Senhor é compassivo e misericordioso, lento em irar-se e grande em benignidade. <br> <b> Lucas 1:50: </b> E a sua misericórdia se estende de geração em geração sobre aqueles que o temem. <br> <b> Salmo 86:15: </b> Mas tu, Senhor, és Deus, cheio de compaixão, e lento para irar-se, e grande em benignidade e em verdade. <br> <b> Miquéias 7:18: </b> Quem é Deus como tu, que perdoa a iniquidade e passa por cima da transgressão do restante da sua herança? Não retém para sempre a sua ira, porque tem prazer na misericórdia. <br> <b> Romanos 9:15: </b> Porque diz a Escritura a Faraó: Para te mostrar o meu poder, e para que o meu nome seja anunciado em toda a terra",
        link: "https://www.bibliaonline.com.br/",
        tags:"compaixão, bondade, graça, amor, perdão",
    },
    {
        versiculos: "Graça",
        lista: "<b> Efésios 2:8: </b> Porque pela graça sois salvos, por meio da fé; e isto não vem de vós, é dom de Deus; <br> <b> Tito 2:11:</b>  Porque se manifestou a graça de Deus, que traz salvação a todos os homens, <br> <b> Romanos 5:2: </b> Pelo qual também temos acesso pela fé a esta graça na qual estamos firmes, e nos gloriamos na esperança da glória de Deus. <br> <b> 2 Coríntios 12:9: </b> E disse-me: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza. De boa vontade, pois, me gloriarei nas minhas fraquezas, para que em mim se manifeste o poder de Cristo. <br> <b> 1 Pedro 5:10: </b> E, depois que tiverdes sofrido um pouco, o Deus de toda a graça, que vos chamou à sua eterna glória em Cristo Jesus, ele mesmo vos aperfeiçoará, confirmará, fortalecerá e alicerçará.",
        link: "https://www.bibliaonline.com.br/",
        tags:"salvação, dom, fé, amor, misericórdia",
    },
    {
        versiculos: "Fé",
        lista: "<b> Romanos 1:17: </b> Porque no evangelho a justiça de Deus se revela, de fé em fé, como está escrito: O justo viverá por fé. <br><b> Hebreus 11:1: </b> Ora, a fé é a certeza de coisas que se esperam, a convicção de fatos que se não veem. <br><b> Marcos 11:22: </b> E Jesus, respondendo, lhes disse: Tende fé em Deus. <br><b> 2 Coríntios 5:7:</b>  Porque andamos por fé, e não por vista. <br><b> João 3:16: </b> Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.",
        link: "https://www.bibliaonline.com.br/",
        tags:"fé, confiança, certeza, convicção, esperança, crendice, Deus, Deus Pai, Filho, Espírito Santo, divindade, criador, salvação, redenção, justificação, vida, vida eterna, propósito, significado, ação, obras, testemunho, serviço",
    },
    {
        versiculos: "Paz",
        lista: "<b> João 14:27: </b> Deixo-lhes a paz; a minha paz lhes dou. Não a dou como o mundo a dá. Não se perturbe o coração de vocês. Creiam em Deus; creiam também em mim.<br><b> Filipenses 4:7: </b> E a paz de Deus, que excede todo o entendimento, guardará os seus corações e os seus pensamentos em Cristo Jesus.<br><b> Isaías 26:3: </b> Tu conservarás em perfeita paz aquele cujo ânimo está firme em ti, porque ele confia em ti.<br><b> Romanos 5:1: </b> Tendo, pois, sido justificados pela fé, temos paz com Deus por meio de nosso Senhor Jesus Cristo.<br><b> Colossenses 3:15: </b> E a paz de Cristo reine em vossos corações, à qual também fostes chamados em um só corpo; e sede agradecidos.",
        link: "https://www.bibliaonline.com.br/",
        tags:"paz, tranquilidade, serenidade, calma, Deus, paz de Deus, Espírito Santo, relacionamentos, harmonia, unidade, amor, mente, tranquilidade, clareza, alma, conforto, consolo",
    },
    {
        versiculos: "Sabedoria",
        lista: "<b> Tiago 1:5: </b> Se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente e não o lança em rosto; e ser-lhe-á dada. <br><b> Provérbios 4:7: </b> Adquire a sabedoria, adquire o entendimento; não a esqueças, nem se aparte de teus olhos. <br><b> Provérbios 9:10: </b> O temor do Senhor é o princípio da sabedoria, e o conhecimento do Santo é o entendimento. <br><b> Colossenses 1:9: </b> E por isso, desde o dia em que ouvimos a respeito de vocês, não havemos cessado de orar por vocês, pedindo que sejam cheios do conhecimento da vontade de Deus em toda sabedoria e entendimento espiritual, <br><b> Provérbios 8:11: </b> Porque a sabedoria é melhor do que as pérolas; e todos os teus deleites não se comparam a ela.",
        link: "https://www.bibliaonline.com.br/",
        tags:"sabedoria, conhecimento, entendimento, discernimento, Deus, temor de Deus, sabedoria divina, vida, decisões, escolhas, conduta, aprendizado, estudo, crescimento, verdade, conhecimento, realidade",
    },
];